version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: study-mentor-api/Dockerfile
    ports:
      - "5000:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge