// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using StudyMentorApi.Data;

#nullable disable

namespace StudyMentorApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260608193000_RemoveDefaultStudyRecords")]
    partial class RemoveDefaultStudyRecords
    {
    }
}
