// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StudyMentorApi.Data;

#nullable disable

namespace StudyMentorApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260607165423_AddTests")]
    partial class AddTests
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pgcrypto");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StudyMentorApi.Data.Models.Card", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Definition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("FlashcardId")
                        .HasColumnType("uuid");

                    b.Property<string>("Term")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FlashcardId");

                    b.ToTable("cards", (string)null);
                });

            modelBuilder.Entity("StudyMentorApi.Data.Models.ChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ChatSessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("completed");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ChatSessionId");

                    b.ToTable("chat_messages", (string)null);
                });

            modelBuilder.Entity("StudyMentorApi.Data.Models.ChatSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("LectureId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LectureId");

                    b.HasIndex("UserId");

                    b.ToTable("chat_sessions", (string)null);
                });

            modelBuilder.Entity("StudyMentorApi.Data.Models.Exercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ChatMessageId")
                        .HasColumnType("uuid");

                    b.Property<string>("ExerciseType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ChatMessageId");

                    b.ToTable("exercises", (string)null);

                    b.HasDiscriminator<string>("ExerciseType").HasValue("Exercise");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("StudyMentorApi.Data.Models.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("groups", (string)null);
                });

            modelBuilder.Entity("StudyMentorApi.Data.Models.Lecture", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.ToTable("lectures", (string)null);
                });

            modelBuilder.Entity("StudyMentorApi.Data.Models.Major", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("majors", (string)null);
                });

            modelBuilder.Entity("StudyMentorApi.Data.Models.Subject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("MajorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MajorId");

                    b.ToTable("subjects", (string)null);
                });

            modelBuilder.Entity("StudyMentorApi.Data.Models.TestAnswerVariant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<Guid>("TestQuestionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TestQuestionId");

                    b.ToTable("test_answer_variants", (string)null);
                });

            modelBuilder.Entity("StudyMentorApi.Data.Models.TestQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TestId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TestId");

                    b.ToTable("test_questions", (string)null);
                });

            modelBuilder.Entity("StudyMentorApi.Data.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("StudyMentorApi.Data.Models.Flashcard", b =>
                {
                    b.HasBaseType("StudyMentorApi.Data.Models.Exercise");

                    b.HasDiscriminator().HasValue("Flashcard");
                });

            modelBuilder.Entity("StudyMentorApi.Data.Models.Test", b =>
                {
                    b.HasBaseType("StudyMentorApi.Data.Models.Exercise");

                    b.Property<Guid?>("SourceFlashcardId")
                        .HasColumnType("uuid");

                    b.HasIndex("SourceFlashcardId");

                    b.HasDiscriminator().HasValue("Test");
                });

            modelBuilder.Entity("StudyMentorApi.Data.Models.Card", b =>
                {
                    b.HasOne("StudyMentorApi.Data.Models.Flashcard", "Flashcard")
                        .WithMany("Cards")
                        .HasForeignKey("FlashcardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flashcard");
                });

            modelBuilder.Entity("StudyMentorApi.Data.Models.ChatMessage", b =>
                {
                    b.HasOne("StudyMentorApi.Data.Models.ChatSession", "ChatSession")
                        .WithMany("Messages")
                        .HasForeignKey("ChatSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChatSession");
                });

            modelBuilder.Entity("StudyMentorApi.Data.Models.ChatSession", b =>
                {
                    b.HasOne("StudyMentorApi.Data.Models.Lecture", "Lecture")
                        .WithMany("ChatSessions")
                        .HasForeignKey("LectureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudyMentorApi.Data.Models.User", "User")
                        .WithMany("ChatSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lecture");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StudyMentorApi.Data.Models.Exercise", b =>
                {
                    b.HasOne("StudyMentorApi.Data.Models.ChatMessage", "ChatMessage")
                        .WithMany("Exercises")
                        .HasForeignKey("ChatMessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChatMessage");
                });

            modelBuilder.Entity("StudyMentorApi.Data.Models.Lecture", b =>
                {
                    b.HasOne("StudyMentorApi.Data.Models.Subject", "Subject")
                        .WithMany("Lectures")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("StudyMentorApi.Data.Models.Subject", b =>
                {
                    b.HasOne("StudyMentorApi.Data.Models.Major", "Major")
                        .WithMany("Subjects")
                        .HasForeignKey("MajorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Major");
                });

            modelBuilder.Entity("StudyMentorApi.Data.Models.TestAnswerVariant", b =>
                {
                    b.HasOne("StudyMentorApi.Data.Models.TestQuestion", "TestQuestion")
                        .WithMany("AnswerVariants")
                        .HasForeignKey("TestQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TestQuestion");
                });

            modelBuilder.Entity("StudyMentorApi.Data.Models.TestQuestion", b =>
                {
                    b.HasOne("StudyMentorApi.Data.Models.Test", "Test")
                        .WithMany("Questions")
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Test");
                });

            modelBuilder.Entity("StudyMentorApi.Data.Models.Test", b =>
                {
                    b.HasOne("StudyMentorApi.Data.Models.Flashcard", "SourceFlashcard")
                        .WithMany()
                        .HasForeignKey("SourceFlashcardId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("SourceFlashcard");
                });

            modelBuilder.Entity("StudyMentorApi.Data.Models.ChatMessage", b =>
                {
                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("StudyMentorApi.Data.Models.ChatSession", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("StudyMentorApi.Data.Models.Lecture", b =>
                {
                    b.Navigation("ChatSessions");
                });

            modelBuilder.Entity("StudyMentorApi.Data.Models.Major", b =>
                {
                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("StudyMentorApi.Data.Models.Subject", b =>
                {
                    b.Navigation("Lectures");
                });

            modelBuilder.Entity("StudyMentorApi.Data.Models.TestQuestion", b =>
                {
                    b.Navigation("AnswerVariants");
                });

            modelBuilder.Entity("StudyMentorApi.Data.Models.User", b =>
                {
                    b.Navigation("ChatSessions");
                });

            modelBuilder.Entity("StudyMentorApi.Data.Models.Flashcard", b =>
                {
                    b.Navigation("Cards");
                });

            modelBuilder.Entity("StudyMentorApi.Data.Models.Test", b =>
                {
                    b.Navigation("Questions");
                });
#pragma warning restore 612, 618
        }
    }
}
